### ISSUE TITLE
Issues in V2.1

### ISSUE THREAD

**Issue by blueforce** [ZEM-Mediamatiker/DIGAME-Handbuch#4]
- Serchresults
  http://digame.zem.ch/search/query:test
  Overlay and arrows shown, please hide
- Desktop Layout
  the printbutton in the topnav is still missing

**Comment by dmamediamatiker** [comment]
searchresults doesn't show the navigation arrows in the next version.
the grey overlay which appears on some keywords is a problem, I haven't found a solution for yet.
The printbutton appears again. Was a problem with the css.
