### ISSUE TITLE
Costum Errorpage

### ISSUE THREAD

**Issue by blueforce** [ZEM-Mediamatiker/DIGAME-Handbuch#5]
A costumised errorpage is still missing
Steps to reproduce:
1. type a invalid URL and hit enter, e.g.: http://digame.zem.ch/swisstopo
2. You get the default errorpage from grav

Pls find a way to redirect to a costumised default 404, something like oops... or so.

**Comment by dmamediamatiker** [comment]
will be included in the next release. thanks.
